package br.com.zup.nimbus.compose.layout.style.model

internal class Container(
    borderWidth: Double?,
    borderDashLength: Double?,
    borderDashSpacing: Double?,
    cornerRadius: Double?,
    borderColor: String?,
    margin: Double?,
    marginStart: Double?,
    marginEnd: Double?,
    marginTop: Double?,
    marginBottom: Double?,
    marginHorizontal: Double?,
    marginVertical: Double?,
    padding: Double?,
    paddingStart: Double?,
    paddingEnd: Double?,
    paddingTop: Double?,
    paddingBottom: Double?,
    paddingHorizontal: Double?,
    paddingVertical: Double?,
    width: AdaptiveSize? = null,
    height: AdaptiveSize? = null,
    directionScope: DirectionScope,
    minWidth: Double?,
    minHeight: Double?,
    maxWidth: Double?,
    maxHeight: Double?,
    clipped: Boolean?,
    backgroundColor: String?,
    shadow: List<Shadow>? = null,
    val crossAxisAlignment: CrossAxisAlignment?,
    val mainAxisAlignment: MainAxisAlignment?,
): Box(
    borderWidth = borderWidth,
    borderDashLength = borderDashLength,
    borderDashSpacing = borderDashSpacing,
    cornerRadius = cornerRadius,
    borderColor = borderColor,
    margin = margin,
    marginStart = marginStart,
    marginEnd = marginEnd,
    marginTop = marginTop,
    marginBottom = marginBottom,
    marginHorizontal = marginHorizontal,
    marginVertical = marginVertical,
    padding = padding,
    paddingStart = paddingStart,
    paddingEnd = paddingEnd,
    paddingTop = paddingTop,
    paddingBottom = paddingBottom,
    paddingHorizontal = paddingHorizontal,
    paddingVertical = paddingVertical,
    width = width,
    height = height,
    directionScope = directionScope,
    minWidth = minWidth,
    minHeight = minHeight,
    maxWidth = maxWidth,
    maxHeight = maxHeight,
    clipped = clipped,
    backgroundColor = backgroundColor,
    shadow = shadow,
)
